before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p ${DOCKER_TOKEN} $CI_REGISTRY

stages:
  - build_image
  - push_image
  - test_image

build_docker_image:
  stage: build_image
  script:
    - docker build -t docker.io/$NAMESPACE/ansible-docker-image/ubi7-ansible:7.7-303-2.9.2 .
  only:
    changes:
      - Dockerfile

push_image_to_repo:
  stage: push_image
  script:
    - docker push docker.io/$NAMESPACE/ansible-docker-image/ubi7-ansible:7.7-303-2.9.2
  only:
    changes:
      - Dockerfile
