name: Docker Ansible Image CI
on:
  push:
    branches: 
      - master
    paths:
    - 'Dockerfile**'
  pull:
    branches: 
      - master
    paths:
    - 'Dockerfile**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Get Tags for alpine
      id: get-tags
      run: |
        echo ::set-output name=ALPINE_TAG::$(cat Dockerfile-Alpine3 | grep FROM | cut -d ":" -f2)
        echo ::set-output name=CENTOS_TAG::$(cat Dockerfile-Centos8 | grep FROM | cut -d ":" -f2)
        echo ::set-output name=REF_VERSION::$(echo ${GITHUB_REF:10})
    ‐ name: alpine-build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adedapomola/ansible-iac
        dockerfile: Dockerfile-Alpine3
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ outputs.get-tags.ALPINE_TAG }}-${{ outputs.get-tags.REF_VERSION}}
    ‐ name: centos-build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adedapomola/ansible-iac
        dockerfile: Dockerfile-Centos8
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ outputs.get-tags.CENTOS_TAG }}-${{ outputs.get-tags.REF_VERSION}}