name: Docker Ansible Image CI
on:
  push:
    branches: 
      - master
    paths:
    - 'Dockerfile**'
  pull_request:
    branches: 
      - master
    paths:
    - 'Dockerfile**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Tags for image
      id: tags
      run: |
        echo ::set-output name=ALPINE_TAG::$(cat Dockerfile.Alpine3 | grep -oP '(?<=FROM )[^ ]*' | sed 's/://')
        echo ::set-output name=CENTOS_TAG::$(cat Dockerfile.Centos8 | grep -oP '(?<=FROM )[^ ]*' | sed 's/://')
        echo ::set-output name=ANSIBLE_VERSION::$(cat Dockerfile.Alpine3 | grep ANSIBLE_VERSION= | cut -d "=" -f2)
        echo ::set-output name=TAG_VERSION::$(echo ${GITHUB_SHA::4})
    - name: Check outputs
      run: |
        echo ${{ steps.tags.outputs.ALPINE_TAG }}-${{ steps.tags.outputs.ANSIBLE_VERSION }}-${{ steps.tags.outputs.TAG_VERSION }}
        echo ${{ steps.tags.outputs.CENTOS_TAG }}-${{ steps.tags.outputs.ANSIBLE_VERSION }}-${{ steps.tags.outputs.TAG_VERSION }}
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: aade/ansible-iac
        path: .
        dockerfile: ./Dockerfile.Centos8
        tags: ${{ steps.tags.outputs.CENTOS_TAG }}-${{ steps.tags.outputs.ANSIBLE_VERSION }}-${{ steps.tags.outputs.TAG_VERSION }}, latest
  
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: aade/ansible-iac
        path: .
        dockerfile: ./Dockerfile.Alpine3
        tags: ${{ steps.tags.outputs.ALPINE_TAG }}-${{ steps.tags.outputs.ANSIBLE_VERSION }}-${{ steps.tags.outputs.TAG_VERSION }}
